 DROP FUNCTION sgm_app.act_datos_predios_censo(); 
 DROP FUNCTION sgm_app.actualiza_estado_regficha(); 
 DROP FUNCTION sgm_app.actualizar_ciudadelas(); 
 DROP FUNCTION sgm_app.actualizar_id_ciudadela(); 
 DROP FUNCTION sgm_app.actualizar_num_validacion_documento(); 
 DROP FUNCTION sgm_app.actualizar_predio_raiz(); 
 DROP FUNCTION sgm_app.actualizar_predios(); 
 DROP FUNCTION sgm_app.actualizar_rubro_reg_acto(); 
 DROP FUNCTION sgm_app.agregar_actos_ordenanza(); 
 DROP FUNCTION sgm_app.calcular_avaluo_alicuota(); 
 DROP FUNCTION sgm_app.categorizar(); 
 DROP FUNCTION sgm_app.categorizar(bigint); 
 DROP FUNCTION sgm_app.clasificar_actos_para_reportes_dinardap(); 
 DROP FUNCTION sgm_app.coeficiente_predial(numeric); 
 DROP FUNCTION sgm_app.coeficiente_predial2(numeric); 
 DROP FUNCTION sgm_app.copiar_normas_construccion(); 
 DROP FUNCTION sgm_app.copiar_normas_construccion_has_retiros(); 
 DROP FUNCTION sgm_app.copiardatos(); 
 DROP FUNCTION sgm_app.crear_ente_extraordinario(character varying, character varying, character varying, bigint); 
 DROP FUNCTION sgm_app.depreciar(integer, integer, bigint); 
 DROP FUNCTION sgm_app.eliminar_entes_repetidos_registro(); 
 DROP FUNCTION sgm_app.emision_anual_predial(bigint); 
 DROP FUNCTION sgm_app.emision_anual_predial_rural(bigint); 
 DROP FUNCTION sgm_app.emision_anual_predial_rural_excel(bigint); 
 DROP FUNCTION sgm_app.emision_predial(bigint, bigint); 
 DROP FUNCTION sgm_app.emision_predial_rural(bigint, bigint, character varying); 
 DROP FUNCTION sgm_app.getimpuesto(bigint, bigint, bigint); 
 DROP FUNCTION sgm_app.llenarnombrecomprobante(); 
 DROP FUNCTION sgm_app.migracion_movimientos_sin_fichas_referencia(); 
 DROP FUNCTION sgm_app.migracion_movimientos_sin_fichas_referencia_mercantil(); 
 DROP FUNCTION sgm_app.migracion_registro_actualizar_mov_cli(); 
 DROP FUNCTION sgm_app.migracion_registro_formato_ci_ruc(double precision, text); 
 DROP FUNCTION sgm_app.migracion_registro_mercantil(); 
 DROP FUNCTION sgm_app.migracion_registro_mercantil_ente(text, bigint, bigint, bigint, bigint, bigint, timestamp without time zone); 
 DROP FUNCTION sgm_app.migracion_registro_movimiento(bigint, bigint); 
 DROP FUNCTION sgm_app.migracion_registro_movimiento_mercantil(bigint, bigint); 
 DROP FUNCTION sgm_app.migracion_registro_propiedad(smallint, bigint, smallint, integer); 
 DROP FUNCTION sgm_app.migracion_registro_propiedad(); 
 DROP FUNCTION sgm_app.migracion_registro_propiedad_ente(text, bigint, bigint, bigint, bigint, bigint, timestamp without time zone); 
 DROP FUNCTION sgm_app.migrar_de_sctnmclie_a_reg_ente_clie(); 
 DROP FUNCTION sgm_app.migrar_entes_smbcatas_to_sgm(); 
 DROP FUNCTION sgm_app.migrar_permiso_parametros(bigint, bigint); 
 DROP FUNCTION sgm_app.migrar_permisos_faltantes(); 
 DROP FUNCTION sgm_app.migrar_permisos_new(); 
 DROP FUNCTION sgm_app.migrar_sctnmclie_a_reg_ente_interv(); 
 DROP FUNCTION sgm_app.migrar_sctnmclie_a_reg_ente_interv_update(); 
 DROP FUNCTION sgm_app.migrar_usuarios(); 
 DROP FUNCTION sgm_app.new_migracion_registro_borra_tablas(); 
 DROP FUNCTION sgm_app.new_registro_actualiza_extras(); 
 DROP FUNCTION sgm_app.new_registro_fichas(); 
 DROP FUNCTION sgm_app.new_registro_fichas_update(); 
 DROP FUNCTION sgm_app.new_registro_migracion_sire(); 
 DROP FUNCTION sgm_app.new_registro_movi_clientes(); 
 DROP FUNCTION sgm_app.new_registro_movi_clientes_act_domicilio(); 
 DROP FUNCTION sgm_app.new_registro_movi_clientes_update(); 
 DROP FUNCTION sgm_app.new_registro_movi_ficha(); 
 DROP FUNCTION sgm_app.new_registro_movi_ficha_update(); 
 DROP FUNCTION sgm_app.new_registro_movi_referencia(); 
 DROP FUNCTION sgm_app.new_registro_movi_referencia_update(); 
 DROP FUNCTION sgm_app.new_registro_movi_varios(); 
 DROP FUNCTION sgm_app.new_registro_movimientos(); 
 DROP FUNCTION sgm_app.new_registro_movimientos_update(); 
 DROP FUNCTION sgm_app.new_registro_registrador(); 
 DROP FUNCTION sgm_app.obtenerid(); 
 DROP FUNCTION sgm_app.organizar_usuarios(); 
 DROP FUNCTION sgm_app.organizar_usuarios_ruc(); 
 DROP FUNCTION sgm_app.pre_migrar_usuarios(); 
 DROP FUNCTION sgm_app.recorrer_funcion(); 
 DROP FUNCTION sgm_app.registrar_permiso_en_catastro_prueba(bigint); 
 DROP FUNCTION sgm_app.registro_propiedad_ficha_versionamiento(bigint, bigint); 
 DROP FUNCTION sgm_app.unificar1(bigint, bigint[]); 
 DROP FUNCTION sgm_app.unificar2(bigint, bigint[], character varying); 
 DROP FUNCTION sgm_app.unificar_nombres_propietarios(integer, integer); 
 DROP FUNCTION sgm_app.update_propietarios_predio_from_registro(); 
 DROP FUNCTION sgm_app.update_reg_ente_judiciales(); 
 DROP FUNCTION sgm_app.update_tipo_suelo_ctlg_item(); 
 DROP FUNCTION sgm_app.valoracion_predio(bigint); 
 DROP FUNCTION sgm_app.valoracion_predio(bigint, integer); 
 DROP FUNCTION sgm_app.verificar_entes_repetidos(); 
